# Generated by Django 4.2.6 on 2023-11-10 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notas', '0003_alter_carrera_options_alter_facultad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('isactive', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('isactive', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacheres',
                'ordering': ['-lastname'],
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.IntegerField(verbose_name='n1')),
                ('n2', models.IntegerField(verbose_name='n2')),
                ('ex1', models.IntegerField(verbose_name='ex1')),
                ('n3', models.IntegerField(verbose_name='n3')),
                ('n4', models.IntegerField(verbose_name='n4')),
                ('ex2', models.IntegerField(verbose_name='ex2')),
                ('isaproved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('isactive', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.facultad')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.teacher')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['student', 'asignatura'],
            },
        ),
    ]
