# Generated by Django 4.2.6 on 2023-11-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_asignatura_semestre_teacher_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='isaproved',
        ),
    ]
