# Generated by Django 4.2.6 on 2023-11-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_remove_notas_isaproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='isaproved',
            field=models.BooleanField(default=True, verbose_name='Aprobado'),
        ),
    ]
