# Generated by Django 4.2.6 on 2023-11-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_notas_isaproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='isaproved',
        ),
    ]
